server:
  port: 8082
  tomcat:
    max-threads: 10
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      file-size-threshold: 5MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 15
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port} # 自定义实例的id
ly:
  oss:
    accessKeyId: LTAI4FsQDNDEMFWuvxjgkP9J  #你自己的accessKeyId
    accessKeySecret: DAGieNVyK5yTbHGU2QSKn4pRAFQHmX #你自己的accessKeySecret
    host: http://image.leyou.com #http://ly-image-imgs.oss-cn-beijing.aliyuncs.com #你自己的bucket名称.oss-cn-beijing.aliyuncs.com # 访问oss的域名，很重要bucket + endpoint
    endpoint: oss-cn-beijing.aliyuncs.com # 你的服务的端点，不一定跟我一样
    dir: ""      # 保存到bucket的某个子目录
    expireTime: 20 # 过期时间，单位是S
    maxFileSize: 5242880 #文件大小限制，这里是5M