server:
  port: 10010
spring:
  application:
    name: ly-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    #服务续费 改为5毫秒一次
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    # instance-id: ${eureka.instance.ip-address}:${server.port} # 自定义实例的id
    #熔断超时时长：6000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 500    # 建立连接所用的时间
  ReadTimeout: 2000    # #建立连接后从服务器读取到可用资源所用的时间
  MaxAutoRetries: 0    # 当前服务的重试次数
  MaxAutoRetriesNextServer: 1  #切换服务重试次数
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试，只对get请求重试
zuul:
  prefix: /api  # 添加路由前缀
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    upload-service: /upload/**
    search-service: /search/** #搜索微服务
ly:
  cors:
    allowedOrigins:
      - http://manage.leyou.com
      - http://www.leyou.com
    allowedCredentials: true
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 3600
    filterPath: "/**"

