server:
  port: 8084
spring:
  application:
    name: page-service
    # 关闭thymeleaf 缓存
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka